from datetime import datetime

from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageTemplate, Frame)

from reportlab.lib.styles import getSampleStyleSheet

def add_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica-Oblique", 9)
    canvas.drawCentredString(doc.pagesize[0] / 2, 20, "Generated by EdMenX")
    canvas.restoreState()

def generate_pdf(summary, results):

    pdf = SimpleDocTemplate("EdMenX_Report.pdf")

    frame = Frame(pdf.leftMargin, pdf.bottomMargin, pdf.width, pdf.height, id="normal")
    pdf.addPageTemplates([PageTemplate(id="footer", frames=frame, onPage=add_footer)])

    styles = getSampleStyleSheet()

    timestamp_style = styles["Normal"].clone("timestamp_style")
    timestamp_style.alignment = 1

    elements = []

    elements.append(Paragraph("EdMenX Recommendation Report", styles["Title"]))

    elements.append(Paragraph(f"{datetime.now().strftime('%d %B %Y | %I:%M %p')}", timestamp_style))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph("Preference Summary:", styles["Heading2"]))
    elements.append(Spacer(1, 5))

    elements.append(Paragraph(summary,styles["Normal"]))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph("Top 3 Recommendations:", styles["Heading2"]))
    elements.append(Spacer(1, 5))

    rankings = ["1.", "2.", "3."]

    for index, city in enumerate(results[:3]):

        elements.append(Paragraph(f"{rankings[index]} {city['city']}", styles["Heading3"]))

        elements.append(Paragraph(f"Score: {city['score']}/100",styles["Normal"]))
        elements.append(Paragraph(f"Confidence: {city['confidence']}", styles["Normal"]))
        elements.append(Paragraph(f"Monthly Expenses: €{city['monthly_expenses']}", styles["Normal"]))
        elements.append(Paragraph(f"Average Rent: €{city['avg_rent']}", styles["Normal"]))
        elements.append(Paragraph(f"Job Score: {city['job_score']}/100", styles["Normal"]))
        elements.append(Paragraph(f"Student Score: {city['student_score']}/100", styles["Normal"]))
        elements.append(Spacer(1, 10))

    elements.append(Paragraph("Comparison Overview:", styles["Heading2"]))
    elements.append(Spacer(1, 5))

    for city in results[:3]:
        comparison_line = (
            f"{city['city']} | "
            f"Expenses: €{city['monthly_expenses']} | "
            f"Rent: €{city['avg_rent']} | "
            f"Job: {city['job_score']}/100 | "
            f"Student: {city['student_score']}/100")
        elements.append(Paragraph(comparison_line, styles["Normal"]))
        elements.append(Spacer(1, 10))

    pdf.build(elements)